# Generated by Django 4.1.4 on 2023-05-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_apertment_is_fur'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='apertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.apertment'),
        ),
    ]
