# Generated by Django 4.1.4 on 2023-05-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_buyer_apertment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='apertment',
            field=models.IntegerField(),
        ),
    ]
