# Generated by Django 4.1.4 on 2023-05-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
