# Generated by Django 4.1.4 on 2023-04-25 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apertment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apertment_Id', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Compound', models.CharField(max_length=5)),
                ('Price', models.IntegerField()),
                ('PriceT', models.CharField(max_length=50)),
                ('Level', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('is_fur', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Delivery', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=5000)),
                ('Elevator', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Balcony', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Security', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Elc_meter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Water_meter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Natural_gas', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Compound', models.CharField(max_length=5)),
                ('Bedrooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('Delivery', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.URLField(max_length=2000)),
                ('Apertment_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.apertment')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connection_Id', models.CharField(max_length=50)),
                ('Apertment_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.apertment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
