# Generated by Django 4.2 on 2023-04-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_apertment_id_alter_apertment_apertment_id_and_more'),
    ]

    operations = [
    ]
