# Generated by Django 4.2 on 2023-04-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230426_2348'),
    ]

    operations = [
    ]
