# Generated by Django 4.2 on 2023-04-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230426_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Apertment_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.apertment'),
        ),
    ]
