# Generated by Django 4.2 on 2023-04-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_image_apertment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Apertment_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.apertment'),
        ),
    ]
