# Generated by Django 4.2 on 2023-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_image_apertment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apertment',
            name='id',
        ),
        migrations.AlterField(
            model_name='apertment',
            name='Apertment_Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
