# Generated by Django 4.2 on 2023-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_apertment_id_alter_apertment_apertment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apertment',
            name='Apertment_Id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
