# Generated by Django 4.2 on 2023-04-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_apertment_id_alter_apertment_apertment_id'),
    ]

    operations = [
    ]
