# Generated by Django 4.2 on 2023-04-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230427_0132'),
    ]

    operations = [
    ]
