# Generated by Django 4.2 on 2023-04-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230427_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apertment',
            name='id',
            field=models.IntegerField(default=1, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(default=1, max_length=50, primary_key=True, serialize=False),
        ),
    ]
