# Generated by Django 4.2 on 2023-04-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_apertment_id_alter_connection_id_and_more'),
    ]

    operations = [
    ]
