# Generated by Django 4.2 on 2023-04-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20230427_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='apertment',
            name='is_fur',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apertment',
            name='Apertment_Id',
            field=models.IntegerField(default=1, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apertment',
            name='id',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Compound',
            field=models.CharField(max_length=5),
        ),
    ]
